defmodule Guesstheface.Nations do
  @moduledoc "Nations adjacency graph"

  @nations %{
    "afghanistan" => ["china", "iran", "pakistan", "tajikistan", "turkmenistan", "uzbekistan"],
    "albania" => ["greece", "italy", "montenegro", "north_macedonia", "kosovo"],
    "algeria" => [
      "italy",
      "libya",
      "mali",
      "mauritania",
      "morocco",
      "niger",
      "spain",
      "tunisia",
      "western_sahara"
    ],
    "american_samoa" => ["samoa", "tonga", "cook_islands", "niue", "tokelau"],
    "andorra" => ["france", "spain"],
    "angola" => ["democratic_republic_of_the_congo", "republic_of_the_congo", "namibia", "zambia"],
    "anguilla" => [
      "antigua_and_barbuda",
      "british_virgin_islands",
      "netherlands",
      "saint_barthelemy",
      "saint_martin",
      "united_states_virgin_islands"
    ],
    "antigua_and_barbuda" => [
      "france",
      "saint_kitts_and_nevis",
      "anguilla",
      "montserrat",
      "saint_barthelemy"
    ],
    "argentina" => ["bolivia", "brazil", "chile", "paraguay", "uruguay"],
    "armenia" => ["azerbaijan", "georgia", "iran", "turkey"],
    "aruba" => ["curacao", "dominican_republic", "venezuela"],
    "australia" => [
      "east_timor",
      "indonesia",
      "new_zealand",
      "papua_new_guinea",
      "solomon_islands",
      "new_caledonia"
    ],
    "austria" => [
      "czech_republic",
      "germany",
      "hungary",
      "italy",
      "liechtenstein",
      "slovakia",
      "slovenia",
      "switzerland"
    ],
    "azerbaijan" => [
      "armenia",
      "georgia",
      "iran",
      "kazakhstan",
      "russia",
      "turkey",
      "turkmenistan"
    ],
    "bahamas" => ["cuba", "haiti", "united_states_of_america", "turks_and_caicos_islands"],
    "bahrain" => ["iran", "qatar", "saudi_arabia"],
    "bangladesh" => ["myanmar", "india"],
    "barbados" => [
      "france",
      "guyana",
      "saint_lucia",
      "saint_vincent_and_the_grenadines",
      "trinidad_and_tobago",
      "venezuela"
    ],
    "belarus" => ["latvia", "lithuania", "poland", "russia", "ukraine"],
    "belgium" => ["france", "germany", "luxembourg", "netherlands", "united_kingdom"],
    "belize" => ["guatemala", "honduras", "mexico"],
    "benin" => ["burkina_faso", "niger", "nigeria", "togo"],
    "bermuda" => ["united_states_of_america"],
    "bhutan" => ["china", "india"],
    "bolivia" => ["argentina", "brazil", "chile", "paraguay", "peru"],
    "bosnia_and_herzegovina" => ["croatia", "montenegro", "serbia"],
    "botswana" => ["namibia", "south_africa", "zambia", "zimbabwe"],
    "brazil" => [
      "argentina",
      "bolivia",
      "colombia",
      "france",
      "guyana",
      "paraguay",
      "peru",
      "suriname",
      "uruguay",
      "venezuela"
    ],
    "british_virgin_islands" => ["anguilla", "puerto_rico", "united_states_virgin_islands"],
    "brunei" => ["china", "malaysia", "philippines", "taiwan", "vietnam"],
    "bulgaria" => [
      "greece",
      "north_macedonia",
      "romania",
      "serbia",
      "turkey",
      "russia",
      "ukraine"
    ],
    "burkina_faso" => ["benin", "cote_d'ivoire", "ghana", "mali", "niger", "togo"],
    "burundi" => ["democratic_republic_of_the_congo", "rwanda", "tanzania"],
    "cambodia" => ["laos", "thailand", "vietnam"],
    "cameroon" => [
      "central_african_republic",
      "chad",
      "republic_of_the_congo",
      "equatorial_guinea",
      "gabon",
      "nigeria"
    ],
    "canada" => ["united_states_of_america", "greenland", "saint_pierre_and_miquelon"],
    "cape_verde" => ["gambia", "mauritania", "senegal"],
    "cayman_islands" => ["cuba", "honduras", "jamaica"],
    "central_african_republic" => [
      "cameroon",
      "chad",
      "democratic_republic_of_the_congo",
      "republic_of_the_congo",
      "south_sudan",
      "sudan"
    ],
    "chad" => ["cameroon", "central_african_republic", "libya", "niger", "nigeria", "sudan"],
    "chile" => ["argentina", "bolivia", "peru"],
    "china" => [
      "afghanistan",
      "bhutan",
      "brunei",
      "india",
      "indonesia",
      "japan",
      "kazakhstan",
      "north_korea",
      "south_korea",
      "kyrgyzstan",
      "laos",
      "malaysia",
      "mongolia",
      "myanmar",
      "nepal",
      "pakistan",
      "philippines",
      "russia",
      "tajikistan",
      "vietnam",
      "hong_kong",
      "macau",
      "taiwan"
    ],
    "colombia" => [
      "brazil",
      "costa_rica",
      "dominican_republic",
      "ecuador",
      "haiti",
      "jamaica",
      "nicaragua",
      "panama",
      "peru",
      "venezuela"
    ],
    "comoros" => ["france", "madagascar", "mozambique", "seychelles", "tanzania"],
    "democratic_republic_of_the_congo" => [
      "angola",
      "burundi",
      "central_african_republic",
      "republic_of_the_congo",
      "rwanda",
      "south_sudan",
      "tanzania",
      "uganda",
      "zambia"
    ],
    "republic_of_the_congo" => [
      "angola",
      "cameroon",
      "central_african_republic",
      "democratic_republic_of_the_congo",
      "gabon"
    ],
    "cook_islands" => ["kiribati", "american_samoa", "niue", "tokelau"],
    "costa_rica" => ["colombia", "ecuador", "nicaragua", "panama"],
    "cote_d'ivoire" => ["burkina_faso", "ghana", "guinea", "liberia", "mali"],
    "croatia" => [
      "bosnia_and_herzegovina",
      "hungary",
      "italy",
      "montenegro",
      "serbia",
      "slovenia"
    ],
    "cuba" => [
      "bahamas",
      "haiti",
      "honduras",
      "jamaica",
      "mexico",
      "united_states_of_america",
      "cayman_islands",
      "navassa_island"
    ],
    "curacao" => ["dominican_republic", "netherlands", "venezuela", "aruba"],
    "cyprus" => ["egypt", "greece", "israel", "lebanon", "syria", "turkey"],
    "czech_republic" => ["austria", "germany", "poland", "slovakia"],
    "denmark" => ["germany", "norway", "poland", "sweden", "united_kingdom"],
    "djibouti" => ["eritrea", "ethiopia", "somalia", "yemen"],
    "dominica" => ["france", "venezuela"],
    "dominican_republic" => [
      "colombia",
      "haiti",
      "venezuela",
      "aruba",
      "curacao",
      "puerto_rico",
      "turks_and_caicos_islands"
    ],
    "east_timor" => ["australia", "indonesia"],
    "ecuador" => ["colombia", "costa_rica", "peru"],
    "egypt" => [
      "cyprus",
      "greece",
      "israel",
      "jordan",
      "libya",
      "saudi_arabia",
      "sudan",
      "turkey",
      "palestine"
    ],
    "el_salvador" => ["guatemala", "honduras", "nicaragua"],
    "equatorial_guinea" => ["cameroon", "gabon", "nigeria", "sao_tome_and_principe"],
    "eritrea" => ["djibouti", "saudi_arabia", "sudan", "ethiopia", "yemen"],
    "estonia" => ["finland", "latvia", "russia", "sweden"],
    "eswatini" => ["mozambique", "south_africa"],
    "ethiopia" => ["djibouti", "eritrea", "kenya", "somalia", "south_sudan", "sudan"],
    "faroe_islands" => ["iceland", "norway", "united_kingdom"],
    "fiji" => [
      "new_zealand",
      "solomon_islands",
      "tonga",
      "tuvalu",
      "vanuatu",
      "new_caledonia",
      "wallis_and_futuna"
    ],
    "finland" => ["estonia", "norway", "russia", "sweden"],
    "france" => [
      "andorra",
      "antigua_and_barbuda",
      "barbados",
      "belgium",
      "brazil",
      "comoros",
      "dominica",
      "germany",
      "italy",
      "luxembourg",
      "madagascar",
      "mauritius",
      "monaco",
      "saint_lucia",
      "spain",
      "switzerland",
      "suriname",
      "united_kingdom",
      "venezuela",
      "guernsey",
      "jersey",
      "montserrat"
    ],
    "gabon" => ["cameroon", "republic_of_the_congo", "equatorial_guinea", "sao_tome_and_principe"],
    "gambia" => ["cape_verde", "senegal"],
    "georgia" => ["armenia", "azerbaijan", "russia", "turkey"],
    "germany" => [
      "austria",
      "belgium",
      "czech_republic",
      "denmark",
      "france",
      "luxembourg",
      "netherlands",
      "poland",
      "sweden",
      "switzerland",
      "united_kingdom"
    ],
    "ghana" => ["burkina_faso", "cote_d'ivoire", "togo"],
    "gibraltar" => ["spain"],
    "greece" => [
      "albania",
      "bulgaria",
      "cyprus",
      "egypt",
      "italy",
      "libya",
      "north_macedonia",
      "turkey"
    ],
    "greenland" => ["canada", "iceland", "jan_mayen", "svalbard"],
    "grenada" => ["saint_vincent_and_the_grenadines", "trinidad_and_tobago", "venezuela"],
    "guam" => ["federated_states_of_micronesia", "northern_mariana_islands"],
    "guatemala" => ["belize", "el_salvador", "honduras", "mexico"],
    "guernsey" => ["france", "united_kingdom", "jersey"],
    "guinea" => ["cote_d'ivoire", "guinea_bissau", "liberia", "mali", "senegal", "sierra_leone"],
    "guinea_bissau" => ["guinea", "senegal"],
    "guyana" => ["barbados", "brazil", "suriname", "trinidad_and_tobago", "venezuela"],
    "haiti" => [
      "bahamas",
      "colombia",
      "cuba",
      "dominican_republic",
      "jamaica",
      "navassa_island",
      "turks_and_caicos_islands"
    ],
    "honduras" => [
      "belize",
      "cuba",
      "el_salvador",
      "guatemala",
      "jamaica",
      "mexico",
      "nicaragua",
      "cayman_islands"
    ],
    "hong_kong" => ["china", "macau"],
    "hungary" => ["austria", "croatia", "romania", "serbia", "slovakia", "slovenia", "ukraine"],
    "iceland" => ["faroe_islands", "greenland", "jan_mayen"],
    "india" => [
      "bangladesh",
      "bhutan",
      "myanmar",
      "china",
      "indonesia",
      "maldives",
      "nepal",
      "pakistan",
      "sri_lanka",
      "thailand"
    ],
    "indonesia" => [
      "australia",
      "china",
      "east_timor",
      "india",
      "malaysia",
      "palau",
      "papua_new_guinea",
      "philippines",
      "singapore",
      "taiwan",
      "thailand",
      "vietnam"
    ],
    "iran" => [
      "afghanistan",
      "armenia",
      "azerbaijan",
      "bahrain",
      "iraq",
      "kuwait",
      "oman",
      "pakistan",
      "qatar",
      "saudi_arabia",
      "turkey",
      "turkmenistan",
      "united_arab_emirates"
    ],
    "iraq" => ["iran", "jordan", "kuwait", "saudi_arabia", "syria", "turkey"],
    "ireland" => ["united_kingdom"],
    "isle_of_man" => ["united_kingdom"],
    "israel" => ["cyprus", "egypt", "jordan", "lebanon", "syria", "palestine"],
    "italy" => [
      "albania",
      "algeria",
      "austria",
      "croatia",
      "france",
      "greece",
      "libya",
      "malta",
      "montenegro",
      "san_marino",
      "slovenia",
      "spain",
      "switzerland",
      "tunisia",
      "vatican_city"
    ],
    "jamaica" => [
      "colombia",
      "cuba",
      "haiti",
      "honduras",
      "nicaragua",
      "cayman_islands",
      "navassa_island"
    ],
    "jan_mayen" => ["iceland", "greenland"],
    "japan" => [
      "china",
      "south_korea",
      "north_korea",
      "philippines",
      "russia",
      "northern_mariana_islands",
      "taiwan"
    ],
    "jarvis_island" => ["kiribati"],
    "jersey" => ["france", "guernsey"],
    "jordan" => ["egypt", "iraq", "israel", "saudi_arabia", "syria", "palestine"],
    "kazakhstan" => ["azerbaijan", "china", "kyrgyzstan", "russia", "turkmenistan", "uzbekistan"],
    "kenya" => ["ethiopia", "somalia", "south_sudan", "tanzania", "uganda"],
    "kingman_reef" => ["kiribati", "palmyra_atoll"],
    "kiribati" => [
      "marshall_islands",
      "nauru",
      "tuvalu",
      "cook_islands",
      "jarvis_island",
      "kingman_reef",
      "palmyra_atoll",
      "tokelau"
    ],
    "north_korea" => ["china", "south_korea", "russia", "japan"],
    "south_korea" => ["china", "japan", "north_korea"],
    "kosovo" => ["albania", "montenegro", "north_macedonia", "serbia"],
    "kuwait" => ["iran", "iraq", "saudi_arabia"],
    "kyrgyzstan" => ["china", "kazakhstan", "tajikistan", "uzbekistan"],
    "laos" => ["myanmar", "cambodia", "china", "thailand", "vietnam"],
    "latvia" => ["belarus", "estonia", "lithuania", "russia", "sweden"],
    "lebanon" => ["cyprus", "israel", "syria"],
    "lesotho" => ["south_africa"],
    "liberia" => ["cote_d'ivoire", "guinea", "sierra_leone"],
    "libya" => [
      "algeria",
      "chad",
      "egypt",
      "greece",
      "italy",
      "malta",
      "niger",
      "sudan",
      "tunisia",
      "turkey"
    ],
    "liechtenstein" => ["austria", "switzerland"],
    "lithuania" => ["belarus", "latvia", "poland", "russia", "sweden"],
    "luxembourg" => ["belgium", "france", "germany"],
    "macau" => ["china", "hong_kong"],
    "madagascar" => ["comoros", "france", "mauritius", "mozambique", "seychelles"],
    "malawi" => ["mozambique", "tanzania", "zambia"],
    "malaysia" => [
      "brunei",
      "china",
      "indonesia",
      "philippines",
      "singapore",
      "thailand",
      "vietnam",
      "taiwan"
    ],
    "maldives" => ["india", "sri_lanka", "mauritius"],
    "mali" => [
      "algeria",
      "burkina_faso",
      "cote_d'ivoire",
      "guinea",
      "mauritania",
      "niger",
      "senegal"
    ],
    "malta" => ["italy", "libya"],
    "marshall_islands" => ["kiribati", "federated_states_of_micronesia", "nauru", "wake_island"],
    "mauritania" => ["algeria", "cape_verde", "mali", "senegal", "western_sahara"],
    "mauritius" => ["france", "madagascar", "seychelles", "maldives"],
    "mexico" => ["belize", "cuba", "guatemala", "honduras", "united_states_of_america"],
    "federated_states_of_micronesia" => ["marshall_islands", "palau", "papua_new_guinea", "guam"],
    "moldova" => ["romania", "ukraine"],
    "monaco" => ["france"],
    "mongolia" => ["china", "russia"],
    "montenegro" => ["albania", "bosnia_and_herzegovina", "croatia", "italy", "serbia", "kosovo"],
    "montserrat" => ["antigua_and_barbuda", "france", "saint_kitts_and_nevis", "venezuela"],
    "morocco" => ["algeria", "portugal", "spain", "western_sahara"],
    "mozambique" => [
      "comoros",
      "eswatini",
      "madagascar",
      "malawi",
      "south_africa",
      "tanzania",
      "zambia",
      "zimbabwe"
    ],
    "myanmar" => ["bangladesh", "china", "india", "laos", "thailand"],
    "namibia" => ["angola", "botswana", "south_africa", "zambia"],
    "nauru" => ["kiribati", "marshall_islands"],
    "navassa_island" => ["cuba", "haiti", "jamaica"],
    "nepal" => ["india", "china"],
    "netherlands" => [
      "belgium",
      "germany",
      "saint_kitts_and_nevis",
      "united_kingdom",
      "venezuela",
      "anguilla",
      "curacao",
      "saint_barthelemy",
      "saint_martin",
      "sint_maarten",
      "united_states_virgin_islands"
    ],
    "new_caledonia" => ["australia", "fiji", "solomon_islands", "vanuatu", "norfolk_island"],
    "new_zealand" => ["australia", "fiji", "norfolk_island"],
    "nicaragua" => ["colombia", "costa_rica", "el_salvador", "honduras", "jamaica", "panama"],
    "niger" => ["algeria", "benin", "burkina_faso", "chad", "libya", "mali", "nigeria"],
    "nigeria" => [
      "benin",
      "cameroon",
      "chad",
      "equatorial_guinea",
      "niger",
      "sao_tome_and_principe"
    ],
    "niue" => ["tonga", "american_samoa", "cook_islands"],
    "norfolk_island" => ["new_zealand", "new_caledonia"],
    "north_macedonia" => ["albania", "bulgaria", "greece", "serbia", "kosovo"],
    "northern_mariana_islands" => ["japan", "guam"],
    "norway" => [
      "denmark",
      "finland",
      "russia",
      "sweden",
      "united_kingdom",
      "faroe_islands",
      "svalbard"
    ],
    "oman" => ["iran", "pakistan", "saudi_arabia", "united_arab_emirates", "yemen"],
    "pakistan" => ["afghanistan", "china", "india", "iran", "oman"],
    "palau" => ["indonesia", "federated_states_of_micronesia", "philippines"],
    "palestine" => ["egypt", "israel", "jordan"],
    "palmyra_atoll" => ["kiribati", "kingman_reef"],
    "panama" => ["colombia", "costa_rica", "nicaragua"],
    "papua_new_guinea" => [
      "australia",
      "indonesia",
      "federated_states_of_micronesia",
      "solomon_islands"
    ],
    "paraguay" => ["argentina", "bolivia", "brazil"],
    "peru" => ["bolivia", "brazil", "chile", "colombia", "ecuador"],
    "philippines" => [
      "brunei",
      "china",
      "indonesia",
      "japan",
      "malaysia",
      "palau",
      "vietnam",
      "taiwan"
    ],
    "poland" => [
      "belarus",
      "czech_republic",
      "denmark",
      "germany",
      "lithuania",
      "russia",
      "slovakia",
      "sweden",
      "ukraine"
    ],
    "portugal" => ["morocco", "spain"],
    "puerto_rico" => [
      "dominican_republic",
      "venezuela",
      "british_virgin_islands",
      "united_states_virgin_islands"
    ],
    "qatar" => ["bahrain", "iran", "saudi_arabia", "united_arab_emirates"],
    "romania" => ["bulgaria", "hungary", "moldova", "russia", "serbia", "ukraine"],
    "russia" => [
      "azerbaijan",
      "belarus",
      "bulgaria",
      "china",
      "estonia",
      "finland",
      "georgia",
      "japan",
      "kazakhstan",
      "north_korea",
      "latvia",
      "lithuania",
      "mongolia",
      "norway",
      "poland",
      "romania",
      "sweden",
      "turkey",
      "ukraine",
      "united_states_of_america",
      "svalbard"
    ],
    "rwanda" => ["burundi", "democratic_republic_of_the_congo", "tanzania", "uganda"],
    "saint_barthelemy" => [
      "antigua_and_barbuda",
      "netherlands",
      "saint_kitts_and_nevis",
      "anguilla",
      "saint_martin",
      "sint_maarten"
    ],
    "saint_kitts_and_nevis" => [
      "antigua_and_barbuda",
      "netherlands",
      "venezuela",
      "montserrat",
      "saint_barthelemy"
    ],
    "saint_lucia" => ["barbados", "france", "saint_vincent_and_the_grenadines", "venezuela"],
    "saint_martin" => ["netherlands", "anguilla", "saint_barthelemy", "sint_maarten"],
    "saint_pierre_and_miquelon" => ["canada"],
    "saint_vincent_and_the_grenadines" => [
      "barbados",
      "grenada",
      "saint_lucia",
      "trinidad_and_tobago",
      "venezuela"
    ],
    "samoa" => ["tonga", "american_samoa", "tokelau", "wallis_and_futuna"],
    "san_marino" => ["italy"],
    "sao_tome_and_principe" => ["equatorial_guinea", "gabon", "nigeria"],
    "saudi_arabia" => [
      "bahrain",
      "egypt",
      "eritrea",
      "iran",
      "iraq",
      "jordan",
      "kuwait",
      "oman",
      "qatar",
      "sudan",
      "united_arab_emirates",
      "yemen"
    ],
    "senegal" => ["cape_verde", "gambia", "guinea", "guinea_bissau", "mali", "mauritania"],
    "serbia" => [
      "bosnia_and_herzegovina",
      "bulgaria",
      "croatia",
      "hungary",
      "montenegro",
      "north_macedonia",
      "romania",
      "kosovo"
    ],
    "seychelles" => ["comoros", "madagascar", "mauritius", "tanzania"],
    "sierra_leone" => ["guinea", "liberia"],
    "singapore" => ["indonesia", "malaysia"],
    "sint_maarten" => ["netherlands", "saint_barthelemy", "saint_martin"],
    "slovakia" => ["austria", "czech_republic", "hungary", "poland", "ukraine"],
    "slovenia" => ["austria", "croatia", "italy", "hungary"],
    "solomon_islands" => ["australia", "fiji", "papua_new_guinea", "vanuatu", "new_caledonia"],
    "somalia" => ["djibouti", "ethiopia", "kenya", "yemen"],
    "south_africa" => ["botswana", "eswatini", "lesotho", "mozambique", "namibia", "zimbabwe"],
    "south_sudan" => [
      "central_african_republic",
      "democratic_republic_of_the_congo",
      "ethiopia",
      "kenya",
      "sudan",
      "uganda"
    ],
    "spain" => [
      "algeria",
      "andorra",
      "france",
      "italy",
      "morocco",
      "portugal",
      "gibraltar",
      "united_kingdom",
      "western_sahara"
    ],
    "sri_lanka" => ["india", "maldives"],
    "sudan" => [
      "central_african_republic",
      "chad",
      "egypt",
      "eritrea",
      "ethiopia",
      "libya",
      "saudi_arabia",
      "south_sudan"
    ],
    "suriname" => ["brazil", "france", "guyana"],
    "svalbard" => ["norway", "russia", "greenland"],
    "sweden" => [
      "denmark",
      "estonia",
      "finland",
      "germany",
      "latvia",
      "lithuania",
      "norway",
      "poland",
      "russia"
    ],
    "switzerland" => ["austria", "france", "italy", "liechtenstein", "germany"],
    "syria" => ["cyprus", "iraq", "israel", "jordan", "lebanon", "turkey"],
    "taiwan" => ["brunei", "china", "indonesia", "japan", "malaysia", "philippines", "vietnam"],
    "tajikistan" => ["afghanistan", "china", "kyrgyzstan", "uzbekistan"],
    "tanzania" => [
      "burundi",
      "comoros",
      "democratic_republic_of_the_congo",
      "kenya",
      "malawi",
      "mozambique",
      "rwanda",
      "seychelles",
      "uganda",
      "zambia"
    ],
    "thailand" => ["myanmar", "cambodia", "india", "indonesia", "laos", "malaysia", "vietnam"],
    "togo" => ["benin", "burkina_faso", "ghana"],
    "tokelau" => ["kiribati", "samoa", "american_samoa", "cook_islands", "wallis_and_futuna"],
    "tonga" => ["fiji", "samoa", "american_samoa", "niue", "wallis_and_futuna"],
    "trinidad_and_tobago" => [
      "barbados",
      "grenada",
      "guyana",
      "saint_vincent_and_the_grenadines",
      "venezuela"
    ],
    "tunisia" => ["algeria", "italy", "libya"],
    "turkey" => [
      "armenia",
      "azerbaijan",
      "bulgaria",
      "cyprus",
      "egypt",
      "georgia",
      "greece",
      "iran",
      "iraq",
      "libya",
      "russia",
      "syria",
      "ukraine"
    ],
    "turkmenistan" => ["afghanistan", "azerbaijan", "iran", "kazakhstan", "uzbekistan"],
    "turks_and_caicos_islands" => ["bahamas", "dominican_republic", "haiti"],
    "tuvalu" => ["fiji", "kiribati", "wallis_and_futuna"],
    "uganda" => ["democratic_republic_of_the_congo", "kenya", "rwanda", "south_sudan", "tanzania"],
    "ukraine" => [
      "belarus",
      "bulgaria",
      "hungary",
      "moldova",
      "poland",
      "romania",
      "russia",
      "slovakia",
      "turkey"
    ],
    "united_arab_emirates" => ["iran", "oman", "qatar", "saudi_arabia"],
    "united_kingdom" => [
      "belgium",
      "denmark",
      "france",
      "germany",
      "ireland",
      "netherlands",
      "norway",
      "spain",
      "faroe_islands",
      "guernsey",
      "isle_of_man"
    ],
    "united_states_of_america" => ["bahamas", "bermuda", "canada", "cuba", "mexico", "russia"],
    "united_states_virgin_islands" => [
      "netherlands",
      "venezuela",
      "anguilla",
      "british_virgin_islands",
      "puerto_rico"
    ],
    "uruguay" => ["argentina", "brazil"],
    "uzbekistan" => ["afghanistan", "kazakhstan", "kyrgyzstan", "tajikistan", "turkmenistan"],
    "vanuatu" => ["fiji", "solomon_islands", "new_caledonia"],
    "vatican_city" => ["italy"],
    "venezuela" => [
      "barbados",
      "brazil",
      "colombia",
      "dominica",
      "dominican_republic",
      "france",
      "grenada",
      "guyana",
      "netherlands",
      "saint_kitts_and_nevis",
      "saint_lucia",
      "saint_vincent_and_the_grenadines",
      "trinidad_and_tobago",
      "aruba",
      "curacao",
      "montserrat",
      "puerto_rico",
      "united_states_virgin_islands"
    ],
    "vietnam" => [
      "brunei",
      "cambodia",
      "china",
      "indonesia",
      "laos",
      "malaysia",
      "philippines",
      "taiwan",
      "thailand"
    ],
    "wake_island" => ["marshall_islands"],
    "wallis_and_futuna" => ["fiji", "samoa", "tonga", "tuvalu", "tokelau"],
    "western_sahara" => ["algeria", "morocco", "mauritania", "spain"],
    "yemen" => ["djibouti", "eritrea", "oman", "saudi_arabia", "somalia"],
    "zambia" => [
      "angola",
      "botswana",
      "democratic_republic_of_the_congo",
      "malawi",
      "mozambique",
      "namibia",
      "tanzania",
      "zimbabwe"
    ],
    "zimbabwe" => ["botswana", "mozambique", "south_africa", "zambia"]
  }

  def all(), do: @nations

  def get_neighbors(nation), do: Map.get(@nations, nation, nil)
end
